name: Smoke Tests (Firefox)



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Smoke Tests
        run: mvn clean verify -Denvironment="run_with_firefox"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "target/site/serenity/SERENITY*.xml"
      - name: Zip Reports
        if: always()
        run: zip test-artifact.zip target/site/serenity/* -r
      - name: Upload Artifact GitHub Action
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifact-for-download
          path: test-artifact.zip
